# Generated by Django 3.1.3 on 2020-11-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
