# Generated by Django 3.1.3 on 2020-11-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201108_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
