# Generated by Django 3.1.3 on 2020-11-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201108_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
